window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Funciones vectoriales y curvas en el espacio", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-curvas-vectoriales", k: "funcion vectorial curva espacio r(t) tangente aceleracion trayectoria" },
  { t: "Longitud de arco y vector tangente unitario", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-longitud-arco", k: "longitud arco vector tangente unitario rapidez integral" },
  { t: "Triedro de Frenet y curvatura", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-frenet", k: "triedro frenet t n b curvatura torsion plano osculador rectificante normal" },
  { t: "Derivadas parciales", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-derivadas-parciales", k: "derivada parcial fx fy segundas mixtas clairaut" },
  { t: "Regla de la cadena multivariable", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-regla-cadena", k: "regla cadena arbol razon cambio relacionada dz/dt" },
  { t: "Diferenciales y aproximación lineal", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-diferenciales", k: "diferencial aproximacion lineal dz propagacion error" },
  { t: "Gradiente y derivada direccional", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-gradiente", k: "gradiente derivada direccional nabla maximo crecimiento" },
  { t: "Plano tangente y recta normal", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-plano-tangente", k: "plano tangente recta normal superficie nivel" },
  { t: "Puntos críticos y criterio de la segunda derivada", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-puntos-criticos", k: "puntos criticos hessiana criterio segunda derivada maximo minimo silla optimos absolutos" },
  { t: "Integrales dobles en coordenadas polares", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-integrales-polares", k: "integral doble polares jacobiano r dr dtheta" },
  { t: "Integrales triples y coordenadas cilíndricas-esféricas", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-integrales-triples", k: "integral triple cilindricas esfericas jacobiano rho phi" },
  { t: "Aplicaciones de integrales múltiples", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-aplicaciones-integrales", k: "masa centro gravedad momento densidad integral multiple" },
  { t: "Triedro de Frenet en una hélice (animación)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#anim-frenet", k: "animacion helice triedro frenet t n b curvatura interactivo" },
  { t: "Curvas de nivel y gradiente (animación)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#anim-gradiente", k: "animacion curvas nivel gradiente derivada direccional interactivo" },
  { t: "Plano tangente móvil (animación)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#anim-plano-tangente", k: "animacion plano tangente superficie paraboloide interactivo" },
  { t: "Suma de Riemann en polares (animación)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#anim-riemann", k: "animacion suma riemann polares particiones jacobiano interactivo" },
  { t: "Trayectoria de una pelota de tenis", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-tenis", k: "ejemplo trayectoria pelota tenis integrar velocidad aceleracion impacto" },
  { t: "Longitud de arco de la trayectoria de un jet", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-longitud-jet", k: "ejemplo longitud arco jet combate" },
  { t: "Triedro de Frenet de una espiral logarítmica", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-frenet-espiral", k: "ejemplo triedro frenet espiral logaritmica plano rectificante" },
  { t: "Parciales mixtas y verificación de Clairaut", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-clairaut", k: "ejemplo parciales mixtas clairaut logaritmo" },
  { t: "Identidad con la regla de la cadena", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-cadena-identidad", k: "ejemplo regla cadena identidad wx wy demostrar" },
  { t: "Derivada direccional de un potencial eléctrico", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-gradiente-potencial", k: "ejemplo derivada direccional potencial electrico gradiente" },
  { t: "Plano tangente a un paraboloide hiperbólico", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-plano-tangente-superficie", k: "ejemplo plano tangente paraboloide hiperbolico" },
  { t: "Centro de gravedad de un sólido homogéneo", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-centro-gravedad", k: "ejemplo centro gravedad solido homogeneo integral triple" },
  { t: "Ejercicio: tangente a una curva paramétrica", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-tangente-curva", k: "ejercicio vector tangente recta tangente curva" },
  { t: "Ejercicio: longitud de una hélice", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-longitud-helice", k: "ejercicio longitud arco helice" },
  { t: "Ejercicio: curvatura constante de una hélice", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-curvatura-helice", k: "ejercicio curvatura helice constante" },
  { t: "Ejercicio: derivadas parciales segundas", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-parciales-segundas", k: "ejercicio derivadas parciales segundas mixtas" },
  { t: "Ejercicio: razón de cambio relacionada de un cilindro", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-razon-cambio-cilindro", k: "ejercicio razon cambio relacionada cilindro volumen regla cadena" },
  { t: "Ejercicio: propagación de error con la ley de gases", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-propagacion-error", k: "ejercicio propagacion error diferencial ley gases" },
  { t: "Ejercicio: máximo crecimiento de una función", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-max-crecimiento", k: "ejercicio gradiente maximo crecimiento" },
  { t: "Ejercicio: extremos absolutos en una región cerrada", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-optimos-region", k: "ejercicio extremos absolutos region cerrada frontera puntos criticos" },
  { t: "Ejercicio: integral doble sobre un disco en polares", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-integral-polar-disco", k: "ejercicio integral doble disco polares" },
  { t: "Ejercicio: volumen de una esfera en esféricas", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-volumen-esfera-esfericas", k: "ejercicio volumen esfera coordenadas esfericas" },
  { t: "Producto punto y producto cruz", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-producto-punto-cruz", k: "producto punto escalar cruz vectorial angulo proyeccion area paralelogramo triple producto" },
  { t: "Rectas y planos en el espacio", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-rectas-planos-espacio", k: "recta plano espacio vector director normal distancia punto plano parametrica simetrica" },
  { t: "Superficies cuádricas", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-cuadricas", k: "superficie cuadrica elipsoide hiperboloide paraboloide cono trazas" },
  { t: "Límites de funciones de varias variables", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-limites-multivariables", k: "limite varias variables trayectoria polares no existe" },
  { t: "Continuidad de funciones de varias variables", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-continuidad-multivariable", k: "continuidad discontinuidad funcion varias variables" },
  { t: "Multiplicadores de Lagrange", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-lagrange", k: "multiplicadores lagrange optimizacion restriccion condicional" },
  { t: "Integrales dobles sobre regiones generales (Fubini)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-integrales-dobles-generales", k: "integral doble fubini region tipo i tipo ii cartesiana" },
  { t: "Campos vectoriales", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-campos-vectoriales", k: "campo vectorial conservativo potencial gradiente" },
  { t: "Integrales de línea", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-integrales-linea", k: "integral linea trabajo campo escalar vectorial teorema fundamental" },
  { t: "Teorema de Green", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-green", k: "teorema green circulacion area region borde" },
  { t: "Rotacional y divergencia", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-rotacional-divergencia", k: "rotacional divergencia rot div campo irrotacional" },
  { t: "Integrales de superficie", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-integrales-superficie", k: "integral superficie flujo parametrizacion" },
  { t: "Teorema de Stokes y Teorema de la divergencia (Gauss)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#tema-stokes-gauss", k: "teorema stokes gauss divergencia flujo superficie cerrada" },
  { t: "Superficies cuádricas rotables (animación)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#anim-cuadricas", k: "animacion cuadricas elipsoide hiperboloide paraboloide cono rotacion interactivo" },
  { t: "Campo vectorial y trabajo acumulado (animación)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#anim-campo-lineal", k: "animacion campo vectorial trabajo integral linea circulacion interactivo" },
  { t: "Teorema de Green: área de una elipse (animación)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#anim-green", k: "animacion teorema green area elipse borde interactivo" },
  { t: "Plano que pasa por tres puntos", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-plano-tres-puntos", k: "ejemplo plano tres puntos producto cruz normal" },
  { t: "Un límite que no existe por trayectorias", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-limite-no-existe", k: "ejemplo limite no existe trayectoria recta" },
  { t: "Un límite que existe (sándwich/polares)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-limite-existe-sandwich", k: "ejemplo limite existe sandwich polares" },
  { t: "Extremos con Lagrange sobre una circunferencia", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-lagrange-elipse", k: "ejemplo lagrange extremos circunferencia restriccion" },
  { t: "Integral doble sobre una región tipo I", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-fubini-regiones", k: "ejemplo integral doble fubini region tipo i" },
  { t: "Trabajo de un campo a lo largo de una curva", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-linea-trabajo", k: "ejemplo trabajo campo vectorial integral linea" },
  { t: "Teorema de Green sobre un triángulo", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-green-triangulo", k: "ejemplo teorema green triangulo circulacion" },
  { t: "Rotacional y divergencia de un campo", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-rotacional-divergencia", k: "ejemplo rotacional divergencia campo vectorial" },
  { t: "Flujo a través de una esfera (Teorema de la divergencia)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ej-divergencia-esfera", k: "ejemplo flujo esfera teorema divergencia gauss" },
  { t: "Ejercicio: producto cruz y ortogonalidad", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-producto-cruz-ortogonal", k: "ejercicio producto cruz ortogonal" },
  { t: "Ejercicio: clasificar una cuádrica y sus trazas", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-clasificar-cuadrica", k: "ejercicio clasificar cuadrica trazas hiperboloide" },
  { t: "Ejercicio: límite que no existe por trayectorias", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-limite-trayectorias", k: "ejercicio limite trayectorias no existe" },
  { t: "Ejercicio: discontinuidad de una función racional", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-continuidad-racional", k: "ejercicio continuidad discontinuidad racional" },
  { t: "Ejercicio: Lagrange para maximizar un producto", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-lagrange-producto", k: "ejercicio lagrange maximizar producto restriccion" },
  { t: "Ejercicio: Lagrange en 3 variables (AM-GM)", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-lagrange-amgm", k: "ejercicio lagrange tres variables amgm minimizar" },
  { t: "Ejercicio: integral doble sobre un triángulo", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-fubini-triangulo", k: "ejercicio integral doble fubini triangulo" },
  { t: "Ejercicio: integral de línea de un campo escalar", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-linea-escalar", k: "ejercicio integral linea escalar segmento" },
  { t: "Ejercicio: área de una elipse con Green", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-green-elipse", k: "ejercicio green area elipse" },
  { t: "Ejercicio: divergencia de un campo simple", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-divergencia-simple", k: "ejercicio divergencia campo vectorial" },
  { t: "Ejercicio: verificar que un campo es conservativo", c: "Cálculo Multivariable", u: "cursos/calculo-multivariable/index.html#ejer-rotacional-conservativo", k: "ejercicio rotacional conservativo campo" }
);
