window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Cálculo Diferencial — Resumen del curso", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#cheat", k: "calculo diferencial resumen del curso formulas unidades" },
  { t: "Límites y continuidad", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-limites-continuidad", k: "limite continuidad tvi weierstrass discontinuidad indeterminacion" },
  { t: "Asíntotas", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-asintotas", k: "asintota vertical horizontal oblicua racional" },
  { t: "Derivada y reglas", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-derivada-reglas", k: "derivada tangente normal producto cociente cadena logaritmica orden superior" },
  { t: "Regla de la cadena", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-cadena", k: "regla de la cadena composicion leibniz du dx" },
  { t: "Derivadas de orden superior", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-orden-superior", k: "derivadas orden superior segunda tercera notacion leibniz concavidad" },
  { t: "Derivación implícita", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-implicita", k: "derivacion implicita y prima factorizar" },
  { t: "Regla de L'Hôpital", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-lhopital", k: "lhopital indeterminacion 0 0 infinito exponencial" },
  { t: "Teoremas de funciones derivables", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-teoremas", k: "fermat rolle valor medio lagrange weierstrass concavidad" },
  { t: "Razón de cambio y diferencial", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-razon-cambio", k: "razon de cambio variaciones relacionadas diferencial aproximacion lineal" },
  { t: "Optimización y análisis de funciones", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#tema-optimizacion", k: "optimizacion puntos criticos maximo minimo criterio segunda derivada" },

  { t: "Animación: recta secante → tangente", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#anim-secante", k: "secante tangente cociente incremental derivada limite h" },
  { t: "Animación: análisis de una cúbica", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#anim-cubica", k: "cubica coeficientes puntos criticos inflexion derivada" },
  { t: "Animación: límites laterales en función a trozos", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#anim-laterales", k: "limites laterales salto discontinuidad trozos" },
  { t: "Animación: caja de volumen máximo", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#anim-caja", k: "optimizacion caja volumen maximo recorte" },

  { t: "Ejemplo: límite trigonométrico con cambio de variable", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-limite-notable", k: "limite notable cambio de variable exponencial control 3" },
  { t: "Ejemplo: función continua por tramos", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-continuidad-tramos", k: "continuidad tramos empalme control 4" },
  { t: "Ejemplo: asíntotas de una racional", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-asintotas-racional", k: "asintotas verticales horizontal racional clase 8" },
  { t: "Ejemplo: L'Hôpital con función oscilante", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-lhopital-oscilante", k: "lhopital oscilante coseno control 6" },
  { t: "Ejemplo: recta tangente e intersecciones con los ejes", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-tangente-cortes", k: "recta tangente cortes ejes control 5" },
  { t: "Ejemplo: regla de la cadena con composición de funciones", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-cadena-composicion", k: "regla de la cadena composicion seno raiz control 5" },
  { t: "Ejemplo: segunda derivada para verificar una ecuación diferencial", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-orden-superior-derivada", k: "derivadas orden superior ecuacion diferencial certamen 3" },
  { t: "Ejemplo: derivación implícita con exponencial y logaritmo", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-implicita-log", k: "derivacion implicita exponencial logaritmo control 6" },
  { t: "Ejemplo: razón de cambio del globo esférico", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-razon-globo", k: "razon de cambio globo esferico volumen radio control 6" },
  { t: "Ejemplo: máximos, mínimos e inflexión de x³/(x-1)", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ej-optimizacion-cociente", k: "maximos minimos inflexion cociente certamen 3" },

  { t: "Ejercicio: límite por factorización", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-limite-factorizacion", k: "limite factorizacion facil" },
  { t: "Ejercicio: tangente y normal", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-tangente-normal", k: "tangente normal derivada facil" },
  { t: "Ejercicio: derivada con regla de la cadena", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-cadena-raiz", k: "regla de la cadena raiz cubica facil" },
  { t: "Ejercicio: puntos de inflexión con la segunda derivada", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-orden-superior-inflexion", k: "derivadas orden superior inflexion concavidad media" },
  { t: "Ejercicio: constante para continuidad", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-continuidad-k", k: "continuidad constante k media" },
  { t: "Ejercicio: asíntota oblicua", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-asintota-oblicua", k: "asintota oblicua division polinomios media" },
  { t: "Ejercicio: L'Hôpital forma 0^0", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-lhopital-0-0", k: "lhopital forma cero cero logaritmo media" },
  { t: "Ejercicio: teorema de Rolle", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-rolle", k: "rolle punto critico dificil" },
  { t: "Ejercicio: teorema del valor medio", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-valor-medio", k: "valor medio lagrange media" },
  { t: "Ejercicio: derivación implícita en un punto", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-implicita-punto", k: "derivacion implicita punto dificil" },
  { t: "Ejercicio: escalera resbalando", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-escalera", k: "razon de cambio relacionada escalera pitagoras media" },
  { t: "Ejercicio: cerca eléctrica junto al río", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-cerca-electrica", k: "optimizacion cerca rio area maxima dificil" },
  { t: "Ejercicio: aproximación con diferencial de raíz cúbica", c: "Cálculo Diferencial", u: "cursos/calculo-diferencial/index.html#ejer-diferencial-raiz", k: "diferencial aproximacion lineal raiz cubica media" }
);
