window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Taller de Obtención y Preparación de Datos — Resumen del curso", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#cheat", k: "numpy pandas nulos outliers wrangling datos resumen" },
  { t: "Arrays NumPy: creación y dimensiones", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-numpy-arrays", k: "ndarray shape ndim size dtype indexado" },
  { t: "Operaciones vectorizadas en NumPy", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-numpy-vectorizado", k: "vectorizacion axis broadcasting sum mean" },
  { t: "Series de Pandas", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-pandas-series", k: "serie indice apply idxmax filtrado" },
  { t: "DataFrames: selección y exploración", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-pandas-dataframes", k: "loc iloc query filtrado booleano head info describe" },
  { t: "Nulos: mecanismos MCAR MAR MNAR", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-nulos-mecanismos", k: "valores faltantes missing mcar mar mnar isnull" },
  { t: "Imputación y eliminación de nulos", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-nulos-imputacion", k: "fillna dropna media mediana moda regla del 5 50" },
  { t: "Detección de outliers", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-outliers", k: "iqr zscore mad isolation forest atipicos" },
  { t: "Muestreo y ordenamiento de datos", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-muestreo-orden", k: "sample frac sort_values estratificado bootstrap" },
  { t: "Duplicados y reemplazo de valores", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-duplicados-reemplazo", k: "duplicated drop_duplicates replace map codigos" },
  { t: "Discretización y funciones apply", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-discretizacion-apply", k: "cut qcut bins apply lambda" },
  { t: "Groupby y agregación", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-groupby", k: "groupby agg transform split apply combine unstack" },
  { t: "concat, merge y join", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-joins", k: "merge join concat inner left right outer how" },
  { t: "Lectura de datos: CSV, Excel, JSON", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-lectura-archivos", k: "read_csv read_excel read_json encoding sep na_values" },
  { t: "Formatos binarios: Pickle, HDF5, Parquet", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-formatos-binarios", k: "pickle hdf5 parquet to_pickle to_parquet velocidad" },
  { t: "Manipulación de cadenas de caracteres (.str) y regex", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-string-metodos", k: "str contains split extract replace regex expresiones regulares" },
  { t: "Reshape: pivot_table, melt, stack/unstack", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-reshape-pivot", k: "pivot_table melt stack unstack multiindex pivoteo despivoteo" },
  { t: "Matplotlib y Seaborn", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-visualizacion", k: "matplotlib seaborn scatterplot histplot heatmap boxplot" },
  { t: "Ética y comunicación de datos", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#tema-etica", k: "etica sesgos privacidad kate crawford comunicacion" },
  { t: "Visualizador: merge / join visual", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#anim-merge", k: "merge join inner left right outer animacion visual" },
  { t: "Visualizador: groupby animado", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#anim-groupby", k: "groupby animacion split apply combine suma promedio" },
  { t: "Visualizador: outliers e IQR", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#anim-outliers", k: "outliers iqr boxplot slider factor" },
  { t: "Visualizador: imputación de nulos", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#anim-imputacion", k: "imputacion nulos media mediana ffill nan" },
  { t: "Ejemplo: vectorización, axis y broadcasting", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-numpy-vectorizado", k: "vectorizacion axis broadcasting numpy" },
  { t: "Ejemplo: selección y filtrado booleano de DataFrame", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-dataframe-filtrado", k: "filtrado booleano query dataframe" },
  { t: "Ejemplo: detectar MAR con crosstab", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-mar-crosstab", k: "crosstab mar mecanismo faltantes" },
  { t: "Ejemplo: imputación nominal por moda de grupo", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-imputacion-grupo", k: "imputar por grupo moda nominal" },
  { t: "Ejemplo: IQR vs Z-score vs MAD", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-outliers-metodos", k: "iqr zscore mad comparacion outliers" },
  { t: "Ejemplo: agg múltiple y transform por grupo", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-groupby-transform", k: "agg transform groupby normalizar" },
  { t: "Ejemplo: pivot_table con totales y melt", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-pivot-melt", k: "pivot_table melt margins ancho largo" },
  { t: "Ejemplo: los cuatro tipos de merge", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-merge-joins", k: "merge inner left right outer empleados departamentos" },
  { t: "Ejemplo: lectura robusta de CSV (encoding)", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ej-lectura-encoding", k: "encoding csv utf-8 latin-1 read_csv" },
  { t: "Ejercicios de Obtención y Preparación de Datos", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-numpy-velocidad", k: "ejercicios pandas numpy taller obtencion datos" },
  { t: "Ejercicio: velocidad NumPy vs for", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-numpy-velocidad", k: "velocidad numpy for time" },
  { t: "Ejercicio: Serie de ventas y filtrado por promedio", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-series-filtro", k: "serie ventas promedio filtrado" },
  { t: "Ejercicio: filtrado con & y query", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-dataframe-query", k: "filtrado and query dataframe" },
  { t: "Ejercicio: porcentaje de nulos por columna", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-porcentaje-nulos", k: "porcentaje nulos isnull columnas" },
  { t: "Ejercicio: media vs mediana con outlier", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-media-vs-mediana", k: "media mediana outlier fillna" },
  { t: "Ejercicio: marcar outliers sin eliminarlos", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-outliers-marca", k: "outliers marcar iqr columna booleana" },
  { t: "Ejercicio: muestreo estratificado por región", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-muestreo-estratificado", k: "muestreo estratificado sample groupby region" },
  { t: "Ejercicio: duplicados y códigos -88", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-duplicados-codigos", k: "duplicados replace codigo no sabe" },
  { t: "Ejercicio: índice de vulnerabilidad con cut y apply", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-indice-vulnerabilidad", k: "cut apply indice vulnerabilidad bins" },
  { t: "Ejercicio: limpieza de correos con .str y regex", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-string-limpieza", k: "str strip contains extract regex email" },
  { t: "Ejercicio: agg y transform por región", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-groupby-agg-transform", k: "agg transform groupby region ingreso" },
  { t: "Ejercicio: melt y pivot_table equivalentes", c: "Obtención de Datos", u: "cursos/obtencion-datos/index.html#ejer-pivot-melt", k: "melt pivot_table ancho largo allclose" }
);
