window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Bootcamp Lenguajes de Programación — Resumen del curso", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#cheat", k: "cpp java csharp poo comparacion lenguajes bootcamp" },
  { t: "Compilación vs interpretación: C++ vs Python", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-paradigmas", k: "compilado interpretado tipado estatico dinamico scanf cin" },
  { t: "Sintaxis y control de flujo en C", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-c-basico", k: "switch do while for printf scanf cine arreglos funciones" },
  { t: "Arreglos y punteros en C++", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-punteros", k: "puntero direccion desreferenciar vector dinamico resize arreglo" },
  { t: "Clases y objetos en C++", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-clases-cpp", k: "class private public constructor this lista de inicializacion const" },
  { t: "Headers y Makefile en C++", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-modular-cpp", k: "ifndef define endif header cpp makefile guarda de inclusion" },
  { t: "Herencia y polimorfismo en Java", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-herencia-java", k: "extends super empleado gerente desarrollador herencia java" },
  { t: "Colecciones y excepciones en Java", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-colecciones-java", k: "arraylist scanner try catch numberformatexception stringbuilder" },
  { t: "Interfaces con Java Swing", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-swing", k: "jframe jbutton jlabel jtextfield actionlistener setbounds swing" },
  { t: "Sintaxis y POO en C#", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-csharp", k: "csharp propiedades virtual override interpolacion main" },
  { t: "Interfaces con WPF", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-wpf", k: "xaml code-behind xname click mediaitem wpf" },
  { t: "Proyecto Dudo: clases anidadas y tuplas", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-dudo", k: "game player tuple random dados dudo clase anidada" },
  { t: "APIs REST con FastAPI", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-fastapi", k: "fastapi pydantic basemodel get post uvicorn endpoint" },
  { t: "Tiempo real con Flask-SocketIO", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-socketio", k: "websocket socketio emit jwt sse tiempo real chat" },
  { t: "Tabla comparativa de sintaxis: Python vs C++ vs Java vs C#", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#tema-tabla-comparativa", k: "comparacion sintaxis declaracion tipos ciclos clases herencia imprimir" },
  { t: "Visualizador: compilar vs interpretar", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#anim-compilacion", k: "pipeline compilacion interpretacion cpp python animacion" },
  { t: "Visualizador: memoria, pila y punteros en C++", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#anim-memoria", k: "pila stack heap monton puntero new delete direccion animacion" },
  { t: "Visualizador: polimorfismo virtual/override en C#", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#anim-polimorfismo", k: "figura rectangulo cuadrado virtual override polimorfismo animacion" },
  { t: "Visualizador: evento → handler (Swing/WPF)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#anim-evento", k: "actionlistener click handler evento boton swing wpf animacion" },
  { t: "Ejemplo: clase Persona con constructor (C++)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-persona", k: "persona cpp constructor this clase" },
  { t: "Ejemplo: separar clase en headers .h/.cpp", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-gamer-headers", k: "gamer videojuego header makefile composicion" },
  { t: "Ejemplo: clase anidada Game::Player y tuple (Dudo)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-dudo-player", k: "game player tuple make_tuple dudo clase anidada" },
  { t: "Ejemplo: herencia Empleado/Gerente/Desarrollador (Java)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-herencia-java", k: "empleado gerente desarrollador extends super main2 java" },
  { t: "Ejemplo: ArrayList + try/catch en Swing", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-colecciones-swing", k: "arraylist try catch stringbuilder numberformatexception swing" },
  { t: "Ejemplo: Figura/Rectangulo/Cuadrado con virtual/override (C#)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-figura-csharp", k: "figura rectangulo cuadrado virtual override propiedades csharp" },
  { t: "Ejemplo: polimorfismo en WPF con MediaItem", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-wpf-mediaitem", k: "mediaitem pelicula videojuego listbox polimorfismo wpf" },
  { t: "Ejemplo: endpoints GET/POST con FastAPI", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ej-fastapi", k: "fastapi pydantic basemodel get post item" },
  { t: "Ejercicios de Bootcamp Lenguajes de Programación", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-cine", k: "ejercicios cpp java csharp fastapi bootcamp" },
  { t: "Ejercicio: precio de cine según edad (C)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-cine", k: "cine precio edad if else if c" },
  { t: "Ejercicio: contar pares y mayores al promedio (C)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-contar-arreglo", k: "arreglo pares promedio control c" },
  { t: "Ejercicio: getters en clase Persona (C++)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-persona-getters", k: "getters persona const cpp encapsulamiento" },
  { t: "Ejercicio: intercambiar variables con punteros (C++)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-swap-punteros", k: "swap intercambiar punteros cpp" },
  { t: "Ejercicio: suma de dados en Game::Player (C++)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-suma-dados", k: "suma dados player vector dudo cpp" },
  { t: "Ejercicio: herencia Cliente/ClientePremium (Java)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-cliente-java", k: "cliente clientepremium extends super java herencia" },
  { t: "Ejercicio: validar edad con Scanner y try/catch (Java)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-edad-scanner", k: "scanner try catch numberformatexception edad java" },
  { t: "Ejercicio: Circulo con virtual/override (C#)", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-circulo-csharp", k: "circulo figura virtual override area perimetro csharp" },
  { t: "Ejercicio: propiedades automáticas en C#", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-propiedades-csharp", k: "propiedades get set producto csharp" },
  { t: "Ejercicio: endpoint POST /usuarios en FastAPI", c: "Bootcamp Lenguajes", u: "cursos/bootcamp-lenguajes/index.html#ejer-fastapi-post", k: "fastapi post usuario pydantic basemodel" }
);
