window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Flujo de trabajo en visualización", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-flujo-trabajo", k: "flujo trabajo preparar estetica graficar personalizar" },
  { t: "Preparación y limpieza de datos", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-preparacion-datos", k: "preparacion limpieza polars concat normalizar dedup melt cut qcut" },
  { t: "Buenas prácticas y personalización", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-buenas-practicas", k: "buenas practicas titulo ejes leyenda escala log anotaciones tight_layout" },
  { t: "Gráficos de relación", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-graficos-relacion", k: "relacion scatter scatterplot pairplot lmplot trendline ols scatter_3d" },
  { t: "Gráficos de distribución", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-graficos-distribucion", k: "distribucion histograma histplot kdeplot boxplot violinplot" },
  { t: "Gráficos de comparación categórica", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-graficos-comparacion", k: "comparacion barras barplot pie torta stacked line_polar radar" },
  { t: "Heatmaps y matrices de correlación", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-heatmaps", k: "heatmap correlacion corr imshow rdbu clustering dendrograma" },
  { t: "Gráficos multivariados avanzados", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-multivariados", k: "multivariado facetas parallel_categories scatter_3d marginal" },
  { t: "Mapas coropléticos y geoespaciales", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-mapas", k: "mapa coropletico geojson choropleth mapbox featureidkey" },
  { t: "Tablas dinámicas", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-tablas-dinamicas", k: "tabla dinamica pivot_table index columns aggfunc fill_value" },
  { t: "Dashboards con Streamlit", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-streamlit", k: "streamlit dashboard cache_data sidebar widgets tabs metric" },
  { t: "Gráficos declarativos con Altair", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-altair", k: "altair mark encode scale domain range declarativo" },
  { t: "Guía de elección de gráfico", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-guia-graficos", k: "guia eleccion tabla que grafico usar pregunta tipo dato" },
  { t: "Elegí el gráfico correcto (visualizador)", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#anim-elegir-grafico", k: "visualizador elegir grafico correcto distribucion relacion comparacion evolucion" },
  { t: "Anatomía de un buen gráfico (visualizador)", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#anim-anatomia-grafico", k: "visualizador anatomia buen grafico titulo ejes leyenda chartjunk" },
  { t: "Correlación interactiva scatter y heatmap (visualizador)", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#anim-heatmap-correlacion", k: "visualizador correlacion interactiva heatmap scatter slider" },
  { t: "Histograma y número de bins (visualizador)", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#anim-histograma-bins", k: "visualizador histograma bins bimodal distribucion" },
  { t: "Unificar y normalizar datos con Polars", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-preparacion-datos", k: "ejemplo polars concat diagonal normalizar region cast" },
  { t: "Scatter con tendencia OLS y marginales", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-scatter-trendline", k: "ejemplo scatter trendline ols marginal histogram happiness" },
  { t: "Boxplot con escala log y KDE comparado", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-distribucion-log", k: "ejemplo boxplot escala log kdeplot common_norm ebay" },
  { t: "Barras con error y gráfico polar", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-comparacion-polar", k: "ejemplo barras error_y line_polar perfil latam" },
  { t: "Matriz de correlación y heatmap clusterizado", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-heatmap-cluster", k: "ejemplo heatmap correlacion clustering dendrograma standardscaler" },
  { t: "Categorías paralelas con qcut", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-multivariados", k: "ejemplo parallel_categories qcut discretizar multivariado" },
  { t: "Mapa de Chile y mapa mundial", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-mapas-coropleticos", k: "ejemplo mapa chile mundial choropleth_mapbox locationmode" },
  { t: "Altair + Streamlit + tabla dinámica exportable", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-altair-streamlit", k: "ejemplo altair streamlit cache_data pivot_table download_button" },
  { t: "Ejercicio: elegir el gráfico correcto", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-elegir-1", k: "ejercicio elegir grafico correcto pregunta" },
  { t: "Ejercicio: problema del gráfico de torta", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-torta-problema", k: "ejercicio torta pie categorias problema" },
  { t: "Ejercicio: scatterplot con hue", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-scatter-hue", k: "ejercicio scatterplot hue tips seaborn" },
  { t: "Ejercicio: elegir escala log", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-escala-log", k: "ejercicio escala log histograma outliers" },
  { t: "Ejercicio: filtrar columnas numéricas antes de corr", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-corr-numerico", k: "ejercicio corr select_dtypes numerico correlacion" },
  { t: "Ejercicio: pivot_table con fill_value", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-pivot-fillvalue", k: "ejercicio pivot_table fill_value nan" },
  { t: "Ejercicio: corregir mapa con regiones grises", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-choropleth-gris", k: "ejercicio choropleth featureidkey region gris bug" },
  { t: "Ejercicio: corregir falta de cache_data", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-cache-data", k: "ejercicio streamlit cache_data lento bug" },
  { t: "Ejercicio: corregir alt.Scale domain range", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-altair-domain", k: "ejercicio altair scale domain range bug color" },
  { t: "Entender el contexto y la audiencia", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-contexto-audiencia", k: "storytelling contexto audiencia big idea knaflic" },
  { t: "Atributos preatentivos", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-atencion-preatentiva", k: "preatentivo color tamano posicion atencion dirigir mirada" },
  { t: "Eliminar el desorden: data-ink ratio y chartjunk", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-eliminar-desorden", k: "data-ink ratio chartjunk tufte desorden grilla leyenda" },
  { t: "Pensar como diseñador", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-pensar-como-disenador", k: "diseno affordance accesibilidad daltonismo iterar" },
  { t: "Contar una historia con datos", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#tema-narrativa-datos", k: "narrativa historia storytelling contexto tension resolucion" },
  { t: "Atención preatentiva antes/después (visualizador)", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#anim-atencion-preatentiva", k: "visualizador atencion preatentiva color gris destacar" },
  { t: "Resaltar una categoría con color preatentivo", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-color-preatentivo", k: "ejemplo color_discrete_map gris destacar preatentivo" },
  { t: "Estructura narrativa en dashboard Streamlit", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ej-narrativa-streamlit", k: "ejemplo narrativa streamlit metric annotation contexto" },
  { t: "Ejercicio: identificar chartjunk en gráfico de torta 3D", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-chartjunk-identificar", k: "ejercicio chartjunk torta 3d sombra grilla" },
  { t: "Ejercicio: mismo dato, dos audiencias distintas", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-contexto-audiencia", k: "ejercicio contexto audiencia directorio analistas" },
  { t: "Ejercicio: corregir color_discrete_map saturado", c: "Visualización de Datos", u: "cursos/visualizacion-datos/index.html#ejer-color-map-roto", k: "ejercicio color_discrete_map saturado preatentivo corregir" }
);
