window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Primitivas básicas", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-primitivas", k: "integral indefinida antiderivada tabla inmediatas constante c" },
  { t: "Integración por sustitución", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-sustitucion", k: "cambio de variable regla de la cadena al reves u du" },
  { t: "Integración por partes", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-partes", k: "uv menos v du ilate ciclica" },
  { t: "Fracciones parciales", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-fracciones", k: "descomposicion funcion racional factores lineales cuadraticos" },
  { t: "Sustitución trigonométrica", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-sust-trig", k: "raiz a2-x2 a2+x2 x2-a2 seno tangente secante triangulo" },
  { t: "Integrales trigonométricas", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-trig", k: "seno coseno potencias impar par angulo doble weierstrass tan x/2" },
  { t: "Integral definida y TFC", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-tfc", k: "teorema fundamental del calculo barrow suma de riemann valor medio" },
  { t: "Área entre curvas", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-area", k: "region techo piso tramos integrar respecto a y" },
  { t: "Volumen de revolución (discos, capas)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-volumen", k: "secciones transversales anillos arandelas capas cilindricas solido" },
  { t: "Centro de masa y Teorema de Pappus", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-pappus", k: "centroide distancia al eje volumen atajo lamina momentos" },
  { t: "Longitud de arco y superficie", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-longitud", k: "pitagoras raiz 1 mas derivada al cuadrado area de superficie" },
  { t: "Coordenadas polares", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-polares", k: "r theta area longitud cardioide doble representacion" },
  { t: "Ecuaciones paramétricas", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-parametricas", k: "x de t y de t pendiente longitud astroide" },
  { t: "Integrales impropias", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-impropias", k: "limite infinito no acotada primera segunda especie comparacion p" },
  { t: "Series numéricas (criterios)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-series", k: "geometrica telescopica razon raiz integral comparacion leibniz alternada" },
  { t: "Series de potencias y Taylor", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#tema-taylor", k: "maclaurin radio de convergencia intervalo seno coseno exponencial arctan" },

  { t: "Animación: sumas de Riemann", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#anim-riemann", k: "rectangulos izquierda derecha medio n sliders convergencia" },
  { t: "Animación: sólido de revolución (discos)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#anim-volumen", k: "disco radio elipse 2.5d perspectiva eje x giro" },
  { t: "Animación: área entre curvas", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#anim-area", k: "sliders a b barrido valor absoluto cruce de curvas" },
  { t: "Animación: polinomios de Taylor", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#anim-taylor", k: "grado n seno exponencial aproximacion polinomio" },

  { t: "Ejemplo: dos primitivas distintas de cos(2x)sin(2x)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-primitivas", k: "constante c infinitas primitivas ejemplo resuelto" },
  { t: "Ejemplo: sustitución u=e^x+1", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-sustitucion", k: "sustitucion no obvia exponencial arctan logaritmo" },
  { t: "Ejemplo: fórmula de reducción I_n por partes", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-partes", k: "recursion x2+a2 elevado a n despejar integral ciclica" },
  { t: "Ejemplo: integral 1/(sin^3 x cos x)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-trig", k: "potencia impar seno coseno fracciones parciales" },
  { t: "Ejemplo: sustitución trig con completar cuadrado", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-sust-trig", k: "raiz (x-2)(4-x) arcoseno triangulo" },
  { t: "Ejemplo: fracciones parciales x^3+8", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-fracciones", k: "factor cuadratico irreducible arctan logaritmo" },
  { t: "Ejemplo: área región compuesta (dos tramos)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-area", k: "y=8/x y=2x y=x/2 techo piso integrar en y" },
  { t: "Ejemplo: volumen por anillos y capas (verificación)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-volumen", k: "y=2x-x2 eje y comparar metodos mismo resultado" },
  { t: "Ejemplo: volumen del toro por Pappus (verificación cruzada)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ej-pappus", k: "centro de masa arandelas semicirculo toro" },

  { t: "Ejercicio: perímetro de una circunferencia (longitud de arco)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-circunferencia", k: "verificacion 2 pi a arcoseno" },
  { t: "Ejercicio: longitud de arco curva polinomial", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-arco-poly", k: "cuadrado perfecto x3 1/(4x)" },
  { t: "Ejercicio: integral impropia x^2 e^-x", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-impropia-gamma", k: "partes dos veces l'hopital converge" },
  { t: "Ejercicio: trompeta de Torricelli", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-torricelli", k: "volumen finito superficie infinita 1/x" },
  { t: "Ejercicio: área r=2cos(theta)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-area-polar", k: "circunferencia polar area" },
  { t: "Ejercicio: perímetro de la cardioide", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-cardioide", k: "r=1+sin theta longitud polar" },
  { t: "Ejercicio: longitud del astroide", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-astroide", k: "x=cos3t y=sin3t parametrica simetria" },
  { t: "Ejercicio: curva paramétrica definida por integrales", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-parametrica-tfc", k: "teorema fundamental del calculo x(t) y(t)" },
  { t: "Ejercicio: serie geométrica y telescópica combinadas", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-serie-mixta", k: "(2n+1)^2/5^n suma exacta" },
  { t: "Ejercicio: serie racional por fracciones parciales", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-serie-telescopica", k: "n(n+1)(n+2) telescopica suma" },
  { t: "Ejercicio: criterios de convergencia de series", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-criterios-convergencia", k: "razon comparacion comparacion al limite factorial logaritmo" },
  { t: "Ejercicio: serie de Taylor de sin(3x)", c: "Cálculo Integral", u: "cursos/calculo-integral/index.html#ejer-taylor-sin3x", k: "maclaurin sustitucion u=3x radio de convergencia" }
);
