window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Taller de Programación — Resumen del curso", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#cheat", k: "python resumen fundamentos taller programacion" },
  { t: "Pseudocódigo y diagramas de flujo", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-pseudocodigo", k: "si mientras para fin_si fin_mientras df diagrama de flujo" },
  { t: "Variables y tipos de datos", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-variables", k: "int float str bool id type casting" },
  { t: "Estructuras de control", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-control", k: "if elif else while for range break continue" },
  { t: "Listas: métodos clave", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-listas", k: "append insert pop remove index sort extend slice" },
  { t: "Diccionarios: métodos clave", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-diccionarios", k: "get items keys values pop clear llave valor" },
  { t: "Tuplas y sets", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-tuplas-sets", k: "tupla inmutable set union interseccion diferencia simetrica" },
  { t: "Strings: métodos clave", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-strings", k: "strip split join replace isdigit lower upper" },
  { t: "Funciones: parámetros y *args", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-funciones", k: "def return parametros argumentos valor por defecto args dry modularidad" },
  { t: "Módulos y librerías", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-modulos", k: "import from os math collections datetime modulo propio" },
  { t: "Manejo de archivos", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-archivos", k: "open with read write append rstrip csv polya" },
  { t: "Programación Orientada a Objetos (POO)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-poo", k: "clase objeto atributo metodo herencia self init str dunder" },
  { t: "Tabla comparativa: lista/tupla/set/dict/string", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-tabla-comparativa", k: "comparacion estructuras de datos ordenada mutable indexada" },
  { t: "Visualizador: trazador de ciclo while", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#anim-ciclo", k: "traza ciclo while linea a linea variables pares impares" },
  { t: "Visualizador: operaciones de lista", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#anim-lista", k: "append insert pop slice index animacion cajas lista" },
  { t: "Visualizador: diccionario insertar/buscar", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#anim-diccionario", k: "diccionario clave valor get insertar actualizar buscar animacion" },
  { t: "Visualizador: pila de llamadas a función", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#anim-pila", k: "call stack pila de llamadas frames push pop return funcion" },
  { t: "Ejemplo: pseudocódigo a Python (pares e impares)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-pseudocodigo", k: "traduccion pseudocodigo python mientras haga while" },
  { t: "Ejemplo: identidad, tipo y valor", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-identidad", k: "id type valor objeto python" },
  { t: "Ejemplo: máximo y promedio de una lista", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-lista-promedio", k: "maximo promedio acumulador lista for" },
  { t: "Ejemplo: diccionario anidado con tuplas y sets", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-dict-tuplas-sets", k: "estudiantes ramos en comun interseccion tupla set diccionario" },
  { t: "Ejemplo: funciones con *args y valores por defecto", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-funciones-args", k: "crear_perfil sumar args valor por defecto" },
  { t: "Ejemplo: módulo propio matematicas.py", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-modulo-propio", k: "matematicas.py calculadora import modulo propio" },
  { t: "Ejemplo: manejo de archivos Radios_planetas", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-archivos-radios", k: "radios_planetas areas_planetas csv rstrip archivos" },
  { t: "Ejemplo: clase Agente y AgenteEspecial (POO)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-poo-agente", k: "agente agenteespecial herencia str dunder poo" },
  { t: "Ejercicios de Taller de Programación", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-traduccion-pseudocodigo", k: "ejercicios python taller de programacion" },
  { t: "Ejercicio: par o impar", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-par-impar", k: "par impar modulo" },
  { t: "Ejercicio: casting seguro de texto a número", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-casting", k: "casting int str typeerror" },
  { t: "Ejercicio: promedio de notas por teclado", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-promedio-teclado", k: "promedio notas input lista for" },
  { t: "Ejercicio: operaciones de lista (insert/pop/slice)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-lista-ops", k: "insert pop slice lista ejercicio" },
  { t: "Ejercicio: inventario con diccionario", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-inventario", k: "inventario diccionario min stock total" },
  { t: "Ejercicio: diferencia simétrica de ramos (sets)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-diferencia-simetrica", k: "diferencia simetrica set interseccion ramos" },
  { t: "Ejercicio: frecuencia de palabras", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-frecuencia-palabras", k: "frecuencia palabras split get diccionario" },
  { t: "Ejercicio: mayor valor con *args sin max()", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-args-max", k: "args mayor maximo sin max funcion" },
  { t: "Ejercicio: módulo propio geometria.py", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-modulo-geometria", k: "geometria area_circulo figura modulo import" },
  { t: "Ejercicio: archivo de temperaturas a CSV clasificado", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-archivo-temperaturas", k: "temperaturas csv clasificar archivos rstrip" },
  { t: "Ejercicio: POO Vehiculo y VehiculoElectrico", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-poo-vehiculo", k: "vehiculo vehiculoelectrico herencia override poo" },
  { t: "Ejercicio: traducción de pseudocódigo dado", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-traduccion-pseudocodigo", k: "traduccion pseudocodigo mientras haga while cont" },
  { t: "Recursión: caso base y caso recursivo", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-recursion", k: "recursion caso base caso recursivo pila de llamadas recursionerror" },
  { t: "Ejemplo: función recursiva potencia(base, exponente)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-recursion", k: "recursion potencia base exponente caso base pila" },
  { t: "Ejercicio: factorial recursivo", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-recursion", k: "factorial recursion caso base funcion recursiva" },
  { t: "Manejo de excepciones (try/except/finally)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#tema-excepciones", k: "try except finally valueerror zerodivisionerror keyerror indexerror manejo de errores" },
  { t: "Ejemplo: pedir un entero válido con try/except (reintento)", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ej-excepciones", k: "try except valueerror reintento input validacion while true" },
  { t: "Ejercicio: división segura con try/except", c: "Taller de Programación", u: "cursos/taller-programacion/index.html#ejer-excepciones", k: "division segura zerodivisionerror try except" }
);
