window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Qué es una EDO: orden, grado, linealidad y PVI", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#que-es-una-edo", k: "ecuacion diferencial orden grado linealidad solucion general particular problema de valor inicial pvi campo de direcciones" },
  { t: "Operadores lineales, existencia y unicidad", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#existencia-unicidad", k: "operadores diferenciales lineales ecuacion diferencial lineal teorema de existencia y unicidad" },
  { t: "EDO lineal de primer orden y factor integrante", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#lineal-factor-integrante", k: "edo lineal primer orden factor integrante forma estandar pvi" },
  { t: "Ejemplo resuelto de una pauta de Control 1 real (factor integrante)", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#lineal-factor-integrante", k: "ejemplo pauta control 1 factor integrante pvi condicion al final" },
  { t: "Variables separables", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#separables", k: "variables separables solucion implicita explicita tecnica de resolucion" },
  { t: "Sobre el peso de una persona (modelo de dieta) — error aritmético del apunte", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#separables", k: "peso de una persona dieta modelo dw dt calorias error aritmetico apunte borbolla c=63,72 c=65,71" },
  { t: "Ley de enfriamiento de Newton", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#separables", k: "ley de enfriamiento de newton temperatura ambiente" },
  { t: "Ecuaciones exactas", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#exactas", k: "ecuaciones exactas criterio my nx construir f funcion potencial" },
  { t: "Ecuaciones no exactas y factor integrante", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#no-exactas", k: "ecuaciones no exactas factor integrante depende de x depende de y" },
  { t: "Homogéneas, coeficientes constantes y Bernoulli", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#homogeneas-bernoulli", k: "ecuacion homogenea sustitucion y=vx coeficientes constantes ecuacion caracteristica bernoulli sustitucion v=y1-n" },
  { t: "Aplicaciones de primer orden: crecimiento, enfriamiento y mezclas", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#aplicaciones-primer-orden", k: "crecimiento y decrecimiento exponencial ley de enfriamiento de newton problemas de mezclas estanque ficha" },
  { t: "Variación de parámetros", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#variacion-parametros", k: "variacion de parametros wronskiano solucion particular segundo orden ficha" },
  { t: "Reducción de orden y coeficientes indeterminados", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#reduccion-orden", k: "reduccion de orden formula de abel coeficientes indeterminados solucion particular ficha" },
  { t: "La ecuación de Euler", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#euler", k: "ecuacion de euler cauchy ecuacion indicial coeficientes variables ficha" },
  { t: "Vibraciones: libres, amortiguadas y forzadas", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#vibraciones", k: "masa resorte vibraciones libres amortiguadas forzadas subamortiguado sobreamortiguado critico ficha" },
  { t: "Transformada de Laplace: definición y linealidad", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#laplace-definicion", k: "transformada de laplace definicion linealidad ficha" },
  { t: "Transformada de Laplace: fórmulas elementales y propiedades", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#laplace-propiedades", k: "transformada de laplace tabla propiedades desplazamiento derivadas multiplicacion por t ficha" },
  { t: "Resolución de EDO con Laplace, convolución y Heaviside", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#laplace-edo", k: "laplace resolucion de edo convolucion funcion escalon heaviside ficha" },
  { t: "Sistemas lineales de primer orden", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#sistemas", k: "sistemas de ecuaciones diferenciales lineales forma matricial ficha" },
  { t: "Reducción y valores propios", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#valores-propios", k: "valores propios vectores propios matriz sistemas lineales solucion general ficha" },
  { t: "Mapa del semestre (Ecuaciones Diferenciales)", c: "Ecuaciones Diferenciales", u: "cursos/ecuaciones-diferenciales/index.html#inicio", k: "mapa del semestre semanas evaluaciones talleres certamenes" }
);
