window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "EDA — Resumen del curso", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#cheat", k: "eda cheat sheet resumen estructura de datos algoritmos" },
  { t: "Complejidad algorítmica (Big-O)", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-complejidad", k: "complejidad big o notacion asintotica logaritmico cuadratico exponencial" },
  { t: "Recursividad", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-recursividad", k: "recursividad caso base caso recursivo factorial hanoi pila de llamadas" },
  { t: "Estructuras lineales: pila, cola, listas", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-lineales", k: "pila cola lista enlazada simple doble lifo fifo push pop enqueue dequeue" },
  { t: "Árboles: BST, AVL, B/B+", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-arboles", k: "arbol binario busqueda bst avl factor de balance rotaciones arbol b b+ recorridos inorden preorden postorden" },
  { t: "Heaps y colas de prioridad", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-heaps", k: "heap min heap max heap cola de prioridad sift up sift down arreglo" },
  { t: "Árbol de Huffman", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-huffman", k: "huffman compresion codigo prefijo greedy abracadabra" },
  { t: "Grafos: BFS, DFS, Dijkstra, Prim, Kruskal", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-grafos", k: "grafos bfs dfs dijkstra prim kruskal matriz de adyacencia lista de adyacencia mst" },
  { t: "Algoritmos de ordenamiento", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-ordenamiento", k: "ordenamiento burbuja insercion seleccion mergesort quicksort" },
  { t: "Tabla comparativa de complejidades (todo el curso)", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#tema-tabla-complejidades", k: "tabla complejidades comparacion estructuras algoritmos repaso certamen" },
  { t: "Visualizadores paso a paso de EDA", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#anim-bst", k: "visualizadores animaciones interactivas eda paso a paso" },
  { t: "Visualizador: ordenamiento burbuja/inserción/quicksort", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#anim-ordenamiento", k: "visualizador ordenamiento burbuja insercion quicksort barras comparaciones intercambios" },
  { t: "Visualizador: BFS vs DFS en un grafo", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#anim-grafo", k: "visualizador bfs dfs grafo cola pila recorrido nodos" },
  { t: "Visualizador: inserción en BST", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#anim-bst", k: "visualizador arbol binario busqueda insercion bst paso a paso" },
  { t: "Visualizador: construcción del árbol de Huffman", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#anim-huffman", k: "visualizador huffman construccion fusion frecuencias codigos" },
  { t: "Ejemplos resueltos de EDA", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ej-complejidad", k: "ejemplos resueltos eda pautas codigo real" },
  { t: "Ejemplo: comparación O(n log n) vs O(n²)", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ej-complejidad", k: "ejemplo comparacion complejidad n log n cuadratico" },
  { t: "Ejemplo: Torres de Hanoi con n=3", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ej-hanoi", k: "ejemplo torres de hanoi traza recursion movimientos" },
  { t: "Ejemplo: rotación AVL caso LL", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ej-avl-rotacion", k: "ejemplo avl rotacion ll insertaravl codigo c" },
  { t: "Ejemplo: Dijkstra sobre tabla de distancias", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ej-dijkstra", k: "ejemplo dijkstra tabla distancias traza python" },
  { t: "Ejemplo: Huffman de ABRACADABRA", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ej-huffman-abracadabra", k: "ejemplo huffman abracadabra codigos frecuencias" },
  { t: "Ejemplo: traza de Quicksort", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ej-quicksort", k: "ejemplo quicksort partition traza codigo c pivote" },
  { t: "Ejercicios propuestos de EDA", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-complejidad", k: "ejercicios propuestos eda soluciones" },
  { t: "Ejercicio: clasificar complejidad de un fragmento", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-complejidad", k: "ejercicio complejidad bucles anidados facil" },
  { t: "Ejercicio: movimientos de Hanoi para n=5", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-hanoi", k: "ejercicio hanoi movimientos formula facil" },
  { t: "Ejercicio: balanceo de paréntesis con pila", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-pila-parentesis", k: "ejercicio pila parentesis balanceados media" },
  { t: "Ejercicio: inserción en BST y recorrido inorden", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-bst-insercion", k: "ejercicio bst insercion recorrido inorden media" },
  { t: "Ejercicio: identificar rotación AVL (RL)", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-avl-rotacion", k: "ejercicio avl rotacion rl dificil" },
  { t: "Ejercicio: construcción de un min-heap", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-heap-construccion", k: "ejercicio heap construccion sift up arreglo media" },
  { t: "Ejercicio: orden de visita BFS y DFS", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-bfs-dfs", k: "ejercicio bfs dfs orden de visita grafo media" },
  { t: "Ejercicio: Dijkstra desde otro nodo", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-dijkstra", k: "ejercicio dijkstra distancias empate dificil" },
  { t: "Ejercicio: Huffman de MISSISSIPPI", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-huffman", k: "ejercicio huffman mississippi codigos bits media" },
  { t: "Ejercicio: comparar Bubble Sort y Quicksort", c: "Estructura de Datos y Algoritmos", u: "cursos/eda/index.html#ejer-ordenamiento", k: "ejercicio bubble sort quicksort comparaciones intercambios dificil" }
);
