window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Números reales, exponentes y radicales", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-numeros-reales", k: "numeros reales exponentes radicales potencias racionalizacion" },
  { t: "Expresiones algebraicas", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-expresiones", k: "productos notables factorizacion expresiones algebraicas racionales" },
  { t: "Ecuaciones", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-ecuaciones", k: "ecuaciones lineales cuadraticas discriminante vieta radicales" },
  { t: "Valor absoluto", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-valor-absoluto", k: "valor absoluto distancia desigualdad" },
  { t: "Inecuaciones", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-inecuaciones", k: "inecuaciones intervalos tabla de signos racionales" },
  { t: "Trigonometría", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-trigonometria", k: "trigonometria seno coseno tangente circulo unitario identidades" },
  { t: "Funciones", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-funciones", k: "funciones dominio recorrido inyectiva inversa composicion paridad" },
  { t: "Función lineal y cuadrática", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-lineal-cuadratica", k: "funcion lineal cuadratica pendiente vertice parabola" },
  { t: "Función exponencial y logarítmica", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-exp-log", k: "funcion exponencial logaritmica logaritmo base" },
  { t: "Funciones trigonométricas", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#tema-funciones-trig", k: "funciones trigonometricas amplitud periodo desfase arcoseno arcocoseno arcotangente" },
  { t: "Animación: parábola y=ax²+bx+c", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#anim-parabola", k: "parabola vertice discriminante raices animacion interactiva" },
  { t: "Animación: transformaciones de funciones", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#anim-transformaciones", k: "transformaciones funciones desplazamiento escala reflexion animacion" },
  { t: "Animación: exponencial vs logaritmo", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#anim-exp-log", k: "exponencial logaritmo base inversa reflejo animacion" },
  { t: "Animación: inecuación con valor absoluto", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#anim-valor-absoluto", k: "valor absoluto inecuacion intervalo recta real animacion" },
  { t: "Ejemplo: potencias y racionalización", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-potencias-radicales", k: "potencias racionalizacion conjugado control 2 ejemplo" },
  { t: "Ejemplo: reducción de expresión algebraica", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-reduccion-algebraica", k: "reduccion expresion algebraica control 2 ejemplo" },
  { t: "Ejemplo: ecuación con radicales", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-ecuacion-radicales", k: "ecuacion radicales solucion extrana control 3 ejemplo" },
  { t: "Ejemplo: inecuación racional", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-inecuacion-racional", k: "inecuacion racional tabla de signos control 3 ejemplo" },
  { t: "Ejemplo: identidad trigonométrica y ángulos de elevación", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-identidad-elevacion", k: "identidad trigonometrica angulo elevacion control 4 ejemplo" },
  { t: "Ejemplo: costo mínimo con función cuadrática", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-costo-minimo", k: "costo minimo vertice parabola control 6 ejemplo" },
  { t: "Ejemplo: ley de enfriamiento de Newton", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-enfriamiento-newton", k: "ley enfriamiento newton exponencial logaritmo control 7 ejemplo" },
  { t: "Ejemplo: amplitud, período y desfase", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-amplitud-periodo", k: "amplitud periodo desfase arcoseno ayudantia 13 ejemplo" },
  { t: "Ejercicio: ecuación con valor absoluto", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-valor-absoluto", k: "ejercicio valor absoluto ecuacion" },
  { t: "Ejercicio: raíces y Vieta", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-vieta", k: "ejercicio vieta raices cuadratica" },
  { t: "Ejercicio: inecuación con valor absoluto", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-inecuacion-va", k: "ejercicio inecuacion valor absoluto intervalo" },
  { t: "Ejercicio: dominio y paridad", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-dominio-paridad", k: "ejercicio dominio paridad funcion impar" },
  { t: "Ejercicio: función inversa", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-inversa", k: "ejercicio funcion inversa racional" },
  { t: "Ejercicio: vértice de parábola", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-vertice-parabola", k: "ejercicio vertice parabola maximo minimo" },
  { t: "Ejercicio: ecuación exponencial", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-exponencial", k: "ejercicio ecuacion exponencial base" },
  { t: "Ejercicio: ecuación logarítmica", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-logaritmica", k: "ejercicio ecuacion logaritmica dominio" },
  { t: "Ejercicio: período de la tangente", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-periodo-tangente", k: "ejercicio periodo tangente asintota" },
  { t: "Ejercicio: identidad trigonométrica", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-identidad-trig", k: "ejercicio identidad trigonometrica demostracion" },
  { t: "Ejercicio: aplicación ángulo de elevación", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ejer-elevacion", k: "ejercicio aplicacion angulo elevacion sistema ecuaciones" },
  { t: "Ejemplo: inecuación con valor absoluto de expresión racional", c: "Introducción al Cálculo", u: "cursos/intro-calculo/index.html#ej-valor-absoluto-racional", k: "valor absoluto racional casos doble desigualdad ejemplo" }
);
