window.INDICE = window.INDICE || [];
window.INDICE.push(
  { t: "Física — Resumen del curso", c: "Física", u: "cursos/fisica/index.html#cheat", k: "fisica cheat sheet resumen del curso formulas mecanica unidades" },
  { t: "Magnitudes, unidades y vectores", c: "Física", u: "cursos/fisica/index.html#tema-vectores", k: "magnitudes unidades vectores analisis dimensional polares cartesianas" },
  { t: "Cinemática 1D", c: "Física", u: "cursos/fisica/index.html#tema-cinematica1d", k: "cinematica mru mrua caida libre distancia desplazamiento" },
  { t: "Cinemática 2D — tiro parabólico", c: "Física", u: "cursos/fisica/index.html#tema-cinematica2d", k: "cinematica 2d tiro parabolico alcance altura maxima itinerario" },
  { t: "Movimiento circular", c: "Física", u: "cursos/fisica/index.html#tema-circular", k: "movimiento circular omega aceleracion centripeta fuerza centripeta periodo frecuencia" },
  { t: "Leyes de Newton y DCL", c: "Física", u: "cursos/fisica/index.html#tema-newton", k: "leyes de newton diagrama cuerpo libre peso normal tension roce plano inclinado" },
  { t: "Trabajo y energía", c: "Física", u: "cursos/fisica/index.html#tema-trabajo-energia", k: "trabajo energia cinetica potencial teorema trabajo energia potencia roce" },
  { t: "Conservación de energía, momentum y colisiones", c: "Física", u: "cursos/fisica/index.html#tema-conservacion-momentum", k: "conservacion energia momentum impulso colisiones elastica inelastica restitucion" },
  { t: "Animaciones interactivas de Física", c: "Física", u: "cursos/fisica/index.html#anim-proyectil", k: "animaciones interactivas fisica simulaciones" },
  { t: "Animación: tiro parabólico", c: "Física", u: "cursos/fisica/index.html#anim-proyectil", k: "animacion tiro parabolico alcance altura maxima angulo velocidad inicial" },
  { t: "Animación: plano inclinado con DCL", c: "Física", u: "cursos/fisica/index.html#anim-plano", k: "animacion plano inclinado dcl roce normal peso desliza equilibrio" },
  { t: "Animación: colisión 1D", c: "Física", u: "cursos/fisica/index.html#anim-colision", k: "animacion colision 1d elastica inelastica momentum energia cinetica" },
  { t: "Animación: movimiento circular uniforme", c: "Física", u: "cursos/fisica/index.html#anim-circular", k: "animacion movimiento circular uniforme velocidad tangente aceleracion centripeta" },
  { t: "Ejemplos resueltos de Física", c: "Física", u: "cursos/fisica/index.html#ej-polares", k: "ejemplos resueltos fisica pautas" },
  { t: "Ejemplo: coordenadas polares a cartesianas", c: "Física", u: "cursos/fisica/index.html#ej-polares", k: "ejemplo coordenadas polares cartesianas arco radio control 1" },
  { t: "Ejemplo: dos piedras con 1 s de diferencia", c: "Física", u: "cursos/fisica/index.html#ej-piedras", k: "ejemplo caida libre piedras itinerario control 2" },
  { t: "Ejemplo: tiro parabólico bajo la horizontal", c: "Física", u: "cursos/fisica/index.html#ej-precipicio", k: "ejemplo tiro parabolico precipicio bajo la horizontal certamen 1" },
  { t: "Ejemplo: radio mínimo de curva", c: "Física", u: "cursos/fisica/index.html#ej-radio-curva", k: "ejemplo radio minimo curva aceleracion lateral movimiento circular" },
  { t: "Ejemplo: rampa con roce y resorte", c: "Física", u: "cursos/fisica/index.html#ej-rampa-resorte", k: "ejemplo rampa roce resorte teorema trabajo energia" },
  { t: "Ejemplo: choque plástico en pista semicircular", c: "Física", u: "cursos/fisica/index.html#ej-loop-choque", k: "ejemplo choque plastico colision pista semicircular energia momentum examen" },
  { t: "Ejercicios propuestos de Física", c: "Física", u: "cursos/fisica/index.html#ejer-vectores", k: "ejercicios propuestos fisica soluciones" },
  { t: "Ejercicio: componentes de un vector", c: "Física", u: "cursos/fisica/index.html#ejer-vectores", k: "ejercicio vector componentes cartesianas polares facil" },
  { t: "Ejercicio: MRUA de un auto", c: "Física", u: "cursos/fisica/index.html#ejer-mrua", k: "ejercicio mrua aceleracion distancia recorrida facil" },
  { t: "Ejercicio: caída libre desde azotea", c: "Física", u: "cursos/fisica/index.html#ejer-caida-libre", k: "ejercicio caida libre azotea tiempo rapidez media" },
  { t: "Ejercicio: tiro parabólico desde el suelo", c: "Física", u: "cursos/fisica/index.html#ejer-tiro-parabolico", k: "ejercicio tiro parabolico alcance altura maxima media" },
  { t: "Ejercicio: curva peraltada", c: "Física", u: "cursos/fisica/index.html#ejer-peralte", k: "ejercicio peralte rapidez minima maxima roce curva media" },
  { t: "Ejercicio: equilibrio con resorte en plano inclinado", c: "Física", u: "cursos/fisica/index.html#ejer-equilibrio-resorte", k: "ejercicio equilibrio resorte plano inclinado deformacion control 3 media" },
  { t: "Ejercicio: sistema de bloques con polea", c: "Física", u: "cursos/fisica/index.html#ejer-polea", k: "ejercicio sistema bloques polea tension aceleracion control 4 dificil" },
  { t: "Ejercicio: coeficiente de restitución", c: "Física", u: "cursos/fisica/index.html#ejer-restitucion", k: "ejercicio coeficiente restitucion choque velocidades finales dificil" },
  { t: "Ejercicio: loop con resorte", c: "Física", u: "cursos/fisica/index.html#ejer-loop-resorte", k: "ejercicio loop resorte compresion minima energia normal dificil" },
  { t: "Conservación de la energía mecánica", c: "Física", u: "cursos/fisica/index.html#tema-conservacion-energia", k: "conservacion energia mecanica fuerzas conservativas no conservativas trabajo no conservativo loop" },
  { t: "Impulso con fuerza variable", c: "Física", u: "cursos/fisica/index.html#tema-impulso-variable", k: "impulso fuerza variable area bajo la curva aproximacion del impulso fuerza promedio" },
  { t: "Ejemplo: resorte con altura que escala al cuadrado de la compresión", c: "Física", u: "cursos/fisica/index.html#ej-resorte-escala", k: "ejemplo resorte compresion altura energia elastica cuadrado escala" },
  { t: "Ejemplo: auto que choca contra una pared", c: "Física", u: "cursos/fisica/index.html#ej-impulso-pared", k: "ejemplo impulso choque pared fuerza promedio momentum" },
  { t: "Ejercicio: conservación de energía con tramo rugoso", c: "Física", u: "cursos/fisica/index.html#ejer-conservacion-energia", k: "ejercicio conservacion energia rampa roce altura media" },
  { t: "Ejercicio: impulso de una pelota que rebota", c: "Física", u: "cursos/fisica/index.html#ejer-impulso", k: "ejercicio impulso pelota rebote fuerza promedio media" }
);
